### ISSUE TITLE
unresolved external symbol vkCmdDrawMeshTasksEXT

### ISSUE THREAD

**Issue by ohmaya** [nvpro-samples/gl_vk_meshlet_cadscene#15] opened 2022-10-28 05:44 UTC
Was Vulkan SDK 1.3.231.1.

Thanks.

**Comment by ohmaya** [comment] 2022-10-28 06:42
**1.3.204.1 passes the building**, 
- however, nvpro_core/nvvk/memorymanagement_vk.cpp > "AllocationID not freed" is hit.
  - Due to "extension not supported: GL_EXT_mesh_shader" so I need a new shaderc_shared.lib?
    - I'm able to build a shaderc_shared.lib in \google\shaderc\build\libshaderc\Debug to replace the one in Vulkan SDK, still does **not elliminate "extension not supported: GL_EXT_mesh_shader"**.

**Comment by pixeljetstream** [comment] 2022-11-01 10:44
thanks.

the build with the latest SDK should be fixed via https://github.com/nvpro-samples/gl_vk_meshlet_cadscene/commit/46842c592e1f088cb221732297df0101141865e3

however we experience some problems with nvidia drivers and the shaderc version that ship with the Vulkan SDK, requiring to disable the extension via commandline `-noextmeshshader` until we resolved whether the issue is in the driver or shaderc.

**Closed as completed** 2023-03-04 11:32 UTC
